#!/usr/bin/env bash

project_dir="$(echo -e "$(find -L $HOME/coding $HOME/.config -mindepth 1 -maxdepth 2 -type d -print)\n$HOME/personal" | fzf)"

# Don't do anything!
if [[ -z $project_dir ]]; then
    echo "No project selected."
    exit 1
fi

project_name="$(basename $project_dir)"

if [[ -z $TMUX ]]; then
    if tmux has-session -t $project_name 2> /dev/null; then
        tmux attach -t $project_name
    else
        tmux new-session -c $project_dir -s $project_name
    fi
else
    if ! tmux has-session -t $project_name 2> /dev/null; then
        tmux new-session -d -c $project_dir -s $project_name
    fi
    tmux switch-client -t $project_name
fi
